server:
  host: 0.0.0.0
  port: 9815
  # 是否开启调试模式, 线上环境请设置为false
  debug: true

website:
  favicon: ./dist/favicon.ico
  robots: ./dist/robots.txt

secret:
  public_key: ./dist/secret/public_key.pem
  private_key: ./dist/secret/private_key.pem