server:
  host: 0.0.0.0
  port: 9815
  # 是否开启调试模式, 线上环境请设置为false
  debug: true

  auto_migrate: true  # 是否自动迁移数据库

  pool: 20  # 最大使用协程数

website:
  static_dir: ./dist/static  # web初始化常用资源路径
  favicon: ./dist/favicon.ico
  robots: ./dist/robots.txt
  tft: ./dist/SIMYOU.TTF  # 图片验证码字体文件

snowflake:
  machine: 1
  service: 1

secret:
  public_key: ./dist/secret/public_key.pem
  private_key: ./dist/secret/private_key.pem

database:
  driver: mysql
  host: 192.168.255.129
  port: 3306
  username: root
  # 使用 go run .\main.go encipher -p 明文密码进行加密
  password: ReLfAqFpBpwL/FTk2KFnpw==
  db: uat
  charset: utf8mb4
  # 连接池最多同时打开的连接数,设置应比服务器的max_connections小.
  # 一般设置为 服务器CPU核心数 * 2 + 服务器有效磁盘数
  # 设置为 0 代表无限制,不限制连接数
  max-open: 5
  # 连接池里最大的空闲连接数,必须比max-open小.
  # 设置为 0 代表不保留空闲连接
  max-idle: 1
  # 连接池里面的连接最大空闲时长.
  # 当连接持续空闲时长达到max-idle-time后,该连接就好被关闭并从连接池移除.
  # 连接没次被使用后,持续空闲时长会被重置.
  max-idle-time: 30
  # 连接池里面的连接最大存活时间
  # 用于限制一个连接使用的最大时长,这个参数有助于防止连接长时间占用资源.
  # 特别是在高并发场景下，可以有效管理连接的生命周期，减少资源浪费和潜在的性能问题.
  # 设置为0,表示不限制连接的使用时长.这意味着连接可以一直使用,直到显式关闭.
  max-lift-time: 60

redis:
  host: 192.168.255.129
  port: 6379
  # 使用 go run .\main.go encipher -p 明文密码进行加密
  password: ReLfAqFpBpwL/FTk2KFnpw==

minio:
  web: http://40on04289kc4.vicp.fun  # 访或代理minio服务器
  host: 192.168.255.129
  port: 9000
  username: root
  password: 2BxJS/ivhAmTIcI2LSgIIbgMVDryONnzrYrkBKEiA3w=
  token:  # 为空即可
  ssl: false
